name: Build, SemVer - FEATURE BRANCH

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  
  build:
      uses: ./.github/workflows/reusable-workflow.yml
      secrets:
        GHB_TOKEN: ${{ secrets.PAT_TOKEN }}