name: Build, SemVer - FEATURE BRANCH

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  
  build:
      uses: ./.github/workflows/reusable-workflow.yml
      secrets:
        jfrog-token: ${{ secrets.ORG_JFROG_RW_TOKEN }}
        GHB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        registry-url: ${{ secrets.REGISTRY_URL }}