name: Build, SemVer - MASTER BRANCH

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

  workflow_dispatch:

jobs:
  
  build:
      uses: ./.github/workflows/reusable-workflow.yml@main
      secrets:
        jfrog-token: ${{ secrets.ORG_JFROG_RW_TOKEN }}
        GHB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        registry-url: ${{ secrets.REGISTRY_URL }}