name: Update package.json version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update version number
        run: |
          # Extract the current version from package.json
          CURRENT_VERSION=$(jq -r '.version' package.json)

          # Generate a new version number by incrementing the patch version
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print $1"."$2"."$3+1}')

          # Update the version in package.json
          jq --arg new_version "$NEW_VERSION" '.version = $new_version' package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add package.json
          git commit -m "Update version number"
          git push
