name: Update Package Version

on:
  push:
    branches:
      - main

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Update package version
        run: |
          npm version patch --no-git-tag-version
          echo "New package version: $npm_package_version"

      - name: Commit and push changes
        run: |
          git config --local user.email "victor.vic.mazeli@gmail.com"
          git config --local user.name "victormazeli"
          git commit -am "Update package version to $npm_package_version"
          git push
